version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        PARENT_VERSION: latest-22
        PORT: 3000
        PORT_DEBUG: 9229
    environment:
      - PORT=3000
      - PORT_DEBUG=9229
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
    command: ["node", "index.js"]
